[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions-internal"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[dev]
  framework = "svelte"